import type { Config } from "tailwindcss";
import typography from "@tailwindcss/typography";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "mcaai-green": "#86C440",
        "on-primary-container": "#00525c",
        "tertiary-container": "#6dc8cc",
        "primary-fixed-dim": "#7fd3e2",
        "surface-container-low": "#f1f4f5",
        primary: "#006875",
        "university-deep-blue": "#003399",
        "on-secondary-container": "#406e00",
        "on-primary-fixed": "#001f24",
        "text-rich-black": "#000A1F",
        "secondary-fixed": "#b4f56b",
        "on-secondary-fixed": "#0f2000",
        "mcaai-teal": "#72C6D5",
        "tertiary-fixed": "#97f1f5",
        "on-surface": "#181c1d",
        "outline-variant": "#bec8cb",
        "on-error": "#ffffff",
        "surface-container-highest": "#e0e3e4",
        "on-tertiary-container": "#005356",
        "tertiary-fixed-dim": "#7ad5d9",
        outline: "#6e797b",
        error: "#ba1a1a",
        "surface-variant": "#e0e3e4",
        "on-primary-fixed-variant": "#004f58",
        background: "#f7fafb",
        "primary-container": "#72c6d5",
        "neutral-surface": "#F8F9FA",
        "secondary-container": "#b1f369",
        "surface-tint": "#006875",
        "inverse-primary": "#7fd3e2",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#002021",
        secondary: "#3d6a00",
        "inverse-on-surface": "$eef1f2",
        "surface-container": "#ebeeef",
        "on-secondary": "$ffffff",
        "on-background": "$181c1d",
        "surface-dim": "#d7dbdb",
        "primary-fixed": "#9cefff",
        surface: "#f7fafb",
        tertiary: "#00696d",
        "on-primary": "$ffffff",
        "on-error-container": "$93000a",
        "surface-bright": "#f7fafb",
        "inverse-surface": "#2d3132",
        "surface-container-high": "#e5e9e9",
        "on-tertiary-fixed-variant": "#004f52",
        "university-gold": "#FDB813",
        "on-surface-variant": "#3e484b",
        "on-secondary-fixed-variant": "#2d5000",
        "secondary-fixed-dim": "#99d852",
        "error-container": "$ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-desktop": "64px",
        "margin-mobile": "16px",
        unit: "8px",
        gutter: "24px",
        "container-max": "1280px",
      },
      fontFamily: {
        "display-xl": ['var(--font-display-xl)', 'sans-serif'],
        "headline-lg": ['var(--font-headline-lg)', 'sans-serif'],
        "body-lg": ['var(--font-body-lg)', 'sans-serif'],
        "label-sm": ['var(--font-label-sm)', 'sans-serif'],
        "headline-lg-mobile": ['var(--font-headline-lg-mobile)', 'sans-serif'],
        "body-md": ['var(--font-body-md)', 'sans-serif'],
        headline: ['var(--font-headline)', 'sans-serif'],
        "headline-sm": ['var(--font-headline)', 'sans-serif'],
        display: ['var(--font-display)', 'sans-serif'],
        body: ['var(--font-body)', 'sans-serif'],
        label: ['var(--font-label)', 'sans-serif'],
        montserrat: ['var(--font-headline)', 'sans-serif'],
      },
      fontSize: {
        "display-xl": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["40px", { lineHeight: "48px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
      typography: {
        DEFAULT: {
          css: {
            '--tw-prose-body': '#3e484b',
            '--tw-prose-headings': '#003399',
            '--tw-prose-links': '#006875',
            '--tw-prose-bold': '#181c1d',
            '--tw-prose-quotes': '#3e484b',
            '--tw-prose-quote-borders': '#72C6D5',
            '--tw-prose-counters': '#6e797b',
            '--tw-prose-bullets': '#72C6D5',
            '--tw-prose-hr': '#bec8cb',
            '--tw-prose-th-borders': '#bec8cb',
            '--tw-prose-td-borders': '#e0e3e4',
            maxWidth: 'none',
            h2: {
              fontFamily: 'var(--font-headline)',
              fontWeight: '700',
              fontSize: '1.5rem',
              lineHeight: '2rem',
              marginTop: '2rem',
              marginBottom: '0.75rem',
              color: '#003399',
            },
            h3: {
              fontFamily: 'var(--font-headline)',
              fontWeight: '600',
              fontSize: '1.25rem',
              marginTop: '1.5rem',
              marginBottom: '0.5rem',
              color: '#003399',
            },
            blockquote: {
              borderLeftColor: '#72C6D5',
              borderLeftWidth: '4px',
              paddingLeft: '1rem',
              fontStyle: 'normal',
              color: '#3e484b',
            },
            'blockquote p': {
              fontStyle: 'italic',
            },
            cite: {
              display: 'block',
              marginTop: '0.5rem',
              fontSize: '0.875rem',
              color: '#6e797b',
              fontStyle: 'normal',
            },
            a: {
              color: '#006875',
              textDecorationColor: '#72C6D5',
              '&:hover': {
                color: '#003399',
              },
            },
            p: {
              marginTop: '0.75rem',
              marginBottom: '0.75rem',
            },
          },
        },
      },
    },
  },
  plugins: [typography],
};

export default config;