export const PUBLIC_PROJECT_SLUGS = [
  'acts-ai4d-dholuo-project',
  'ai4d-hub-for-ai-and-disability-inclusion',
  'mozilla-common-voice-alternative-language-data-licenses',
  'african-next-voices-pilot-data-collection-in-kenya',
  'ai4ksl-bridging-language-barrier-using-ai-for-kenyan-sign-language',
  'kenyan-languages-corpus-for-nlp-and-machine-translation',
  'kencorpus-kenyan-language-corpus-for-nlp-and-machine-learning',
  'building-nlp-text-and-speech-datasets-for-low-resourced-languages-in-east-africa',
] as const;

export const importProjects = [
  {
    slug: 'acts-ai4d-dholuo-project',
    title: 'ACTS - AI4D DHOLUO PROJECT',
    short_title: 'ACTS Project',
    subtitle: 'AI for climate resilience and farmer advisory systems',
    status: 'Ongoing',
    start_date: '2025-01-01',
    sector: 'agriculture',
    focus: ['Agriculture', 'Speech Technology', 'Machine Translation', 'Data Collection'],
    description:
      'The main goal of this project is to develop a model for transcribing dholuo speech to text and text to speech conversations. The main focus is towards the agricultural context of the Luo community.',
    outcome: {
      aim: 'Our Mission is to harness Artificial Intelligence to preserve, promote and advance the Dholuo language, Culture and Heritage through communication, education, research and digital inclusion. We aim to develop a model for transcribing dholuo speech to text and text to speech conversations, with a focus on the agricultural context of the Luo community.',
      context: 'Smallholder farmers lack reliable, local-language access to agronomic guidance, market prices and climate-adaptive systems that they can communicate with in their own language; access barriers disproportionately affect women and remote communities.',
      tasks: 'Collect multilingual speech and text data, build translation and language-ID components, develop a field-facing advisory pipeline, and integrate with local extension services.',
      success: 'A deployed advisory prototype that delivers voice and text guidance in local languages, measurable increases in farmer access to recommendations, and documentation for scale-up.',
    },
    lead_name: 'dr-vivian-oloo',
    member_names: ['dr-vivian-oloo', 'starnley-odiwuor', 'valary-otieno'],
    funder_names: ['INOVATION FOR DEVELOPMENT (I4D)', 'AFRICAN CENTRE FOR TECHNOLOGY STUDIES (ACTS)'],
    links: [
      { label: 'Project Profile', href: 'https://mcaai.maseno.ac.ke/' },
      { label: 'LinkedIn', href: 'https://www.linkedin.com/company/107030600/admin/dashboard/' },
    ],
    order: 1,
  },
  {
    slug: 'ai4d-hub-for-ai-and-disability-inclusion',
    title: 'AI4D Hub for AI and Disability Inclusion',
    short_title: 'AI4D Hub',
    subtitle: 'Africa-wide coordination for disability-inclusive AI',
    status: 'Active',
    start_date: '2026-01-01',
    end_date: '2028-12-31',
    sector: 'disability',
    focus: ['Disability Inclusion', 'Responsible AI', 'Data Governance', 'Innovation Ecosystems'],
    description:
      'The AI4D Hub for AI and Disability Inclusion is a continent-wide coordination platform that promotes disability-inclusive AI across the full AI lifecycle. It brings together researchers, innovators, policymakers, disability advocates and institutions to advance datasets, coordination, governance frameworks and inclusive AI ecosystems for persons with disabilities in Africa.',
    outcome: {
      aim: 'Build an inclusive AI ecosystem that improves outcomes for persons with disabilities across Africa.',
      context: 'Fragmented efforts and lack of coordinated funding and datasets have limited disability-inclusive AI progress across African institutions.',
      tasks: 'Coordinate partners, document best practices, develop shared datasets, run capacity-building activities and pilot inclusive technologies.',
      success: 'A Hub that enables collaborative projects, shared datasets and policy influence leading to demonstrable improvements in accessibility and inclusion.',
    },
    lead_name: 'Dr. Lilian Wanzare',
    member_names: ['Dr. Lilian Wanzare', 'Jerry John Kponyo', 'Maseno University team', 'Kwame Nkrumah University of Science and Technology partners'],
    funder_names: ['IDRC', 'AI4D Funders Collaborative', 'FCDO', 'Sida', 'Community Jameel'],
    links: [
      { label: 'IDRC Project Page', href: 'https://idrc-crdi.ca/en/what-we-do/projects-we-support/project/ai4d-hub-ai-and-disability-inclusion' },
      { label: 'AI4D Project Page', href: 'https://www.ai4d.ai/projects/hub-for-ai-and-disability-inclusion' },
      { label: 'Project Website', href: 'https://haidiai4d.org/' },
    ],
    order: 2,
  },
  {
    slug: 'mozilla-common-voice-alternative-language-data-licenses',
    title: 'Mozilla Common Voice funded Project: Piloting Alternative Language Data Licenses',
    short_title: 'Common Voice Licensing',
    subtitle: 'Community-centered licensing for African language datasets',
    status: 'Completed',
    start_date: '2025-01-01',
    sector: 'data_governance',
    focus: ['Data Governance', 'Language Data', 'Open Data Licensing', 'Community Consent'],
    description:
      'This Mozilla Common Voice-supported project explored alternative language data licensing models that better reflect the realities of community ownership, consent and fair benefit sharing for African language data. It focused on practical pathways to make language data more ethically open while preserving community rights and accountability.',
    outcome: {
      aim: 'Pilot alternative licensing that balances openness with community rights for language datasets.',
      context: 'Standard open licenses often fail to capture community-level consent and benefit-sharing needs in low-resource language contexts.',
      tasks: 'Engage communities, draft model licenses, run pilot datasets and document guidance for researchers and partners.',
      success: 'Published guidance and piloted datasets demonstrating workable licensing approaches sensitive to community governance.',
    },
    lead_name: 'Dr. Gabriel Oliko',
    member_names: ['Dr. Gabriel Oliko', 'MCAAI research team', 'Community stakeholders', 'Mozilla Common Voice partners'],
    funder_names: ['Mozilla Foundation', 'Common Voice program'],
    links: [
      { label: 'Maseno University Update', href: 'https://www.maseno.ac.ke/common-voice-piloting-alternative-language-data-licenses-workshop-kenya-maseno-university' },
      { label: 'Mozilla Common Voice', href: 'https://www.mozillafoundation.org/en/common-voice/in-country-programmes/' },
      { label: 'Dhonam dataset', href: 'https://huggingface.co/Anv-ke' },
    ],
    order: 3,
  },
  {
    slug: 'african-next-voices-pilot-data-collection-in-kenya',
    title: 'African Next Voices: Pilot Data Collection in Kenya',
    short_title: 'African Next Voices',
    subtitle: 'Speech and text collection for grassroots language inclusion',
    status: 'Completed',
    start_date: '2024-01-01',
    end_date: '2025-12-31',
    sector: 'data_collection',
    focus: ['Data Collection', 'Speech Data', 'Low-resource Languages', 'Community Participation'],
    description:
      'African Next Voices focused on pilot data collection in Kenya to create language resources for underrepresented communities. The project centered on transcription, speech recording and community engagement in Dholuo and Kalenjin contexts, supporting the development of more representative and locally grounded AI systems.',
    outcome: {
      aim: 'Create pilot speech and text resources that enable downstream language technology for underrepresented Kenyan languages.',
      context: 'Lack of representative datasets for many African languages prevents practical ML systems from being built and deployed for local communities.',
      tasks: 'Run community recording sessions, transcribe and annotate data, and publish pilot datasets with community agreements.',
      success: 'Pilot datasets published, local researchers trained, and demonstrator models showing improved local-language performance.',
    },
    lead_name: 'Dr. Vivian Oloo',
    member_names: ['Dr. Vivian Oloo', 'Research associates', 'Community contributors', 'Digital Umuganda collaborators'],
    funder_names: ['Gates Foundation', 'African Next Voices partners'],
    links: [
      { label: 'Maseno workshop update', href: 'https://www.maseno.ac.ke/africa-next-voices-transcription-training-workshop-dholuo-and-kalenjin-communities-held-kisumu' },
      { label: 'TRT Afrika article', href: 'https://www.trtafrika.com/english/article/359e1362af39' },
      { label: 'Hugging Face', href: 'https://huggingface.co/Anv-ke' },
      { label: 'Hackathon with Digital Umuganda', href: 'https://mcaai.maseno.ac.ke/' },
    ],
    order: 4,
  },
  {
    slug: 'ai4ksl-bridging-language-barrier-using-ai-for-kenyan-sign-language',
    title: 'AI4KSL: Bridging Language Barrier using Artificial Intelligence for Kenyan Sign Language among Deaf Learners',
    short_title: 'AI4KSL',
    subtitle: 'AI-powered sign language translation for inclusive education',
    status: 'Ongoing',
    start_date: '2023-01-01',
    end_date: '2024-12-31',
    sector: 'disability',
    focus: ['Disability Inclusion', 'Computer Vision', 'Sign Language', 'Education'],
    description:
      'AI4KSL is designed to reduce language barriers for deaf learners by combining computer vision, sign-language data collection and avatar-based translation. The project creates accessible tools for learners, teachers and communities, helping to bridge communication gaps in education and digital access.',
    outcome: {
      aim: 'Develop practical AI tools that support Kenyan Sign Language recognition and translation for educational contexts.',
      context: 'Deaf learners face access barriers in education due to a lack of scalable KSL interpretation and digital tools.',
      tasks: 'Collect sign-language corpora, train computer-vision models, develop avatar/translation interfaces, and pilot in classrooms.',
      success: 'Demonstrated prototypes that improve classroom communication and documented workflows for further deployment.',
    },
    lead_name: 'Ezekiel Maina',
    member_names: ['Ezekiel Maina', 'Valary Atieno', 'Dr. Samwel Oonge', 'MCAAI disability inclusion team'],
    funder_names: ['EduAI Fund', 'MCAAI partners', 'Community and institutional stakeholders'],
    links: [
      { label: 'YouTube Demo', href: 'https://www.youtube.com/watch?v=5jmfr2hDFDo' },
      { label: 'Maseno University Feature', href: 'https://www.maseno.ac.ke/node/1850' },
      { label: 'Second Demo', href: 'https://www.youtube.com/watch?v=oH046ATSWtU' },
    ],
    order: 5,
  },
  {
    slug: 'kenyan-languages-corpus-for-nlp-and-machine-translation',
    title: 'Kenyan Languages Corpus for Natural Language Processing and Machine Translation',
    short_title: 'UNESCO TWAS-BMBF Corpus',
    subtitle: 'Seed grant for low-resource language technology',
    status: 'Completed',
    start_date: '2023-01-01',
    end_date: '2024-12-31',
    sector: 'nlp',
    focus: ['Machine Translation', 'NLP', 'Corpus Linguistics', 'Low-resource Languages'],
    description:
      'This UNESCO TWAS-BMBF Seed Grant project focused on building a Kenyan-language corpus for natural language processing and machine translation. It supported postgraduate researchers and advanced linguistic resource creation for core Kenyan languages, with a strong emphasis on open, useful and sustainable language data infrastructure.',
    outcome: {
      aim: 'Produce annotated and curated corpora that support machine translation and NLP across Kenyan languages.',
      context: 'A shortage of well-annotated corpora limits research and tool-building for Kenyan languages.',
      tasks: 'Collect, annotate, and curate corpora; support postgraduate research and publish resources.',
      success: 'Open datasets and published research that enable translation and language modelling experiments.',
    },
    lead_name: 'Dr. Vivian Oloo',
    member_names: ['Dr. Vivian Oloo', 'Ezekiel Maina', 'Nelson Odhiambo', 'Edwin Onkoba', 'Maureen', 'MCAAI NLP research associates'],
    funder_names: ['UNESCO', 'TWAS', 'BMBF', 'SG-NAPI'],
    links: [
      { label: 'ACL Anthology Paper', href: 'https://aclanthology.org/2023.jlcl-2.1/' },
      { label: 'arXiv Paper', href: 'https://arxiv.org/abs/2210.16537' },
      { label: 'ACM Paper', href: 'https://dl.acm.org/doi/full/10.1145/3578553' },
      { label: 'MCAAI Research Archive', href: 'https://mcaai.maseno.ac.ke/' },
    ],
    order: 6,
  },
  {
    slug: 'kencorpus-kenyan-language-corpus-for-nlp-and-machine-learning',
    title: 'KenCorpus: Kenyan Language Corpus for NLP and Machine Learning',
    short_title: 'KenCorpus',
    subtitle: 'Text and speech resources for Swahili, Dholuo and Luhya',
    status: 'Completed',
    start_date: '2021-01-01',
    end_date: '2022-12-31',
    sector: 'nlp',
    focus: ['NLP', 'Speech Data', 'Machine Learning', 'Low-resource Languages'],
    description:
      'KenCorpus was a Lacuna Fund-supported project designed to build a Kenyan-language corpus that could support NLP and machine learning tasks across major Kenyan languages. The project created text and speech data resources for Swahili, Dholuo and Luhya and produced proof-of-concept systems for speech recognition and question answering.',
    outcome: {
      aim: 'Create open text and speech resources to enable NLP and ML for Kenyan languages.',
      context: 'Many Kenyan languages lack curated datasets needed for reliable ML models.',
      tasks: 'Collect corpora, validate annotations, release datasets and produce demo systems.',
      success: 'Open public-domain corpora and demonstration systems used by researchers and practitioners.',
    },
    lead_name: 'Dr. Vivian Oloo',
    member_names: ['Dr. Vivian Oloo', 'Barack Wanjawa', 'Florence Indede', 'Owen McOnyango', 'Edward Ombui', 'Lawrence Muchemi'],
    funder_names: ['Lacuna Fund'],
    links: [
      { label: 'KenCorpus site', href: 'https://kencorpus.maseno.ac.ke/' },
      { label: 'Stakeholder workshop', href: 'https://www.maseno.ac.ke/kenCorpus-workshop' },
      { label: 'Workshop review', href: 'https://www.maseno.ac.ke/kencorpus-workshop-review' },
      { label: '2022 update', href: 'https://www.maseno.ac.ke/kencorpus-2022' },
      { label: 'ACL Anthology paper', href: 'https://aclanthology.org/2023.jlcl-2.1/' },
      { label: 'arXiv paper', href: 'https://arxiv.org/abs/2210.16537' },
      { label: 'ACM article', href: 'https://dl.acm.org/doi/full/10.1145/3578553' },
    ],
    order: 7,
  },
  {
    slug: 'building-nlp-text-and-speech-datasets-for-low-resourced-languages-in-east-africa',
    title: 'Building NLP Text and Speech Datasets for Low Resourced Languages in East Africa',
    short_title: 'East Africa Dataset Initiative',
    subtitle: 'Collaborative text and speech resource development',
    status: 'Completed',
    start_date: '2021-01-01',
    end_date: '2022-12-31',
    sector: 'nlp',
    focus: ['Speech Data', 'Text Data', 'East Africa', 'Collaborative AI'],
    description:
      'This project focused on building text and speech datasets for low-resource languages in East Africa, with a particular emphasis on Kiswahili and related language contexts. It was developed through collaborative work with research partners and built on open, community-conscious data practices.',
    outcome: {
      aim: 'Generate reusable language resources and workflows for low-resource East African languages.',
      context: 'Cross-border collaboration and shared resource practices are needed to scale dataset creation across the region.',
      tasks: 'Coordinate partners, collect and annotate corpora, and publish shared datasets and guidance.',
      success: 'Reusable datasets and published methods that inform subsequent regional datasets and research.',
    },
    lead_name: 'MCAAI research team',
    member_names: ['MCAAI team', 'Makerere team', 'Regional language collaborators'],
    funder_names: ['Lacuna Fund', 'Partner research institutions'],
    links: [
      { label: 'OpenReview paper', href: 'https://openreview.net/forum?id=SO-U99z4U-q' },
      { label: 'MCAAI Research Archive', href: 'https://mcaai.maseno.ac.ke/' },
    ],
    order: 8,
  },
];

export const importCollaboration = {
  slug: 'haidi',
  title: 'HAIDI at MCAAI',
  partner: 'HAIDI',
  summary:
    "Africa's first continent-wide coordination platform ensuring that AI development is grounded in inclusive design and directly shaped by disability communities across the continent.",
  body: 'HAIDI was established through a consortium of four institutions spanning Kenya, Ghana, and pan-African civil society. Rather than building one tool in one country, HAIDI coordinates evidence, innovation, and governance across Africa simultaneously — because disability inclusion in AI requires all three to move together.',
  cover_image: 'https://res.cloudinary.com/daecietav/image/upload/v1782476744/Gemini_Generated_Image_nxphqsnxphqsnxph_n3qqpd.png',
  objectives: [
    {
      n: '01',
      title: 'Building the Evidence Base',
      body: 'Developing Africa-centric disability datasets and data governance frameworks to enable inclusive AI development that reflects the realities of disability communities across the continent.',
      accent: 'primary',
    },
    {
      n: '02',
      title: 'Innovation & Scaling',
      body: 'Selecting and scaling high-potential AI innovations that expand opportunities for persons with disabilities — from idea to deployment, with direct community validation through the Live Lab Network.',
      accent: 'mcaai-green',
    },
    {
      n: '03',
      title: 'Governance Integration',
      body: 'Embedding disability rights and accessibility standards into national and regional AI governance frameworks across Africa, ensuring policy keeps pace with — and actively guides — innovation.',
      accent: 'mcaai-teal',
    },
  ],
  contribution_heading: 'Turning policy into working technology',
  contribution_body:
    'Within HAIDI, MCAAI leads the evidence and data governance workstream — and demonstrates what that evidence enables in practice. Our AI4KSL system translates spoken English into Kenyan Sign Language avatar animations in real time, trained on a dataset of over 20,000 annotated sign language videos.\n\nThis work directly advances inclusive education and workplace accessibility for deaf and hard-of-hearing communities in Kenya — and provides a replicable model for other HAIDI partners working on comparable language and communication access challenges across the continent.',
  stat_value: '20K+',
  stat_label: 'Annotated KSL videos',
  stat_description:
    'The AI4KSL training dataset — one of the largest Kenyan Sign Language computational datasets in existence — built at MCAAI as part of the HAIDI evidence base programme.',
  evidence_items: [
    '3,000+ hours of African speech data',
    'NOODL open data governance framework',
    'Africa-centric disability dataset protocols',
  ],
  cta_heading: 'Partner with HAIDI or collaborate with MCAAI',
  cta_body:
    'Whether you are a disability-inclusive AI venture seeking funding, a researcher interested in the evidence base programme, or an institution looking to embed accessibility into AI governance — there is a role for you in HAIDI.',
  links: [
    { label: 'View AI4KSL Project', href: '/projects/ai4ksl-bridging-language-barrier-using-ai-for-kenyan-sign-language' },
  ],
  related_project_slug: 'ai4ksl-bridging-language-barrier-using-ai-for-kenyan-sign-language',
  is_published: true,
  order: 1,
};

export const importInnovations = [
  {
    slug: 'smartvoice-system',
    name: 'SmartVoice System',
    category: 'Voice contribution and validation platform',
    subtitle: 'Voice contribution and validation platform for Kikuyu and Kalenjin',
    date: '25 August 2026',
    description:
      'Voice contribution and validation platform for Kikuyu and Kalenjin, covering ASR and TTS collection, review workflows, and language-lead quality governance.',
    impact: 'Builds inclusive speech datasets for Kenya’s underrepresented languages while keeping data quality and contributor safety in view.',
    summary:
      'SmartVoice is a community voice data platform for Kikuyu and Kalenjin that supports contributor onboarding, qualification, ASR recording, TTS capture, review pipelines, and lead-level governance.',
    overview:
      'The system keeps data quality and contributor safety at the centre of the workflow. Contributors complete profiles and consent, pass a voice qualification, are assigned to ASR or TTS work, and submit recordings that pass a browser and server quality gate before they count toward the corpus.',
    stack: ['ASR', 'TTS', 'Language QA', 'Review workflows'],
    features: [
      'ASR and TTS recording pathways for Kikuyu and Kalenjin communities.',
      'Contributor onboarding, voice qualification, consent capture, and assignment workflow.',
      'Reviewer listening and bulk-approval for pending ASR clips.',
      'Language-lead review, task assignment, and flag handling control.',
      'Server-side audio quality validation for duration, noise, silence, and SNR checks.',
    ],
    users: [
      { role: 'Contributor', description: 'Record qualifying voice samples and contribute to ASR or TTS tasks after assignment.' },
      { role: 'Reviewer', description: 'Approve or reject ASR clips once their account is activated by a lead or admin.' },
      { role: 'Language lead', description: 'Manage one language, validate qualifications, assign tasks, and handle flags.' },
      { role: 'Admin', description: 'Operate the full platform across both languages, users, recordings, and audits.' },
    ],
    useCases: [
      'Sign up and verify email for contributors and reviewers.',
      'Complete profile and consent requirements before access is granted.',
      'Record a two-line qualification script to qualify for work.',
      'Claim ASR or TTS sentences and submit recordings.',
      'Review ASR clips in single or bulk listening flows.',
      'Approve or reject reviewer applications and sentence flags.',
    ],
    frontend: [
      'Landing page highlighting the two languages and two recording paths.',
      'Dashboard with onboarding status, progress milestones, and assignment state.',
      'Speak workflow with waveform, quality feedback, and sentence claim logic.',
      'Listen and bulk-listen desks for ASR review and decision capture.',
      'Lead and admin consoles for validation, user management, and operational oversight.',
    ],
    backend: [
      'App Router backend with middleware for session management, role gates, and maintenance mode.',
      'JWT-based session cookie and role-aware API authorization for authenticated requests.',
      'Supabase Postgres for users, languages, recordings, qualification storage, and review history.',
      'Supabase Storage for WAV assets and separate qualification and corpus buckets.',
      'Shared audio quality gate that blocks silent, noisy, short, or low-SNR recordings before corpus insertion.',
    ],
    details: [
      ['Primary languages', 'Kikuyu and Kalenjin'],
      ['Core projects', 'ASR and TTS'],
      ['Quality gate', 'Duration, noise floor, edge silence, and SNR validation'],
      ['Review model', 'Single or batch approval for ASR after submission'],
      ['Governance', 'Language leads and admins manage assignment and validation'],
    ],
    access_url: '',
    is_published: true,
    order: 1,
  },
  {
    slug: 'tafsiri',
    name: 'Tafsiri',
    category: 'Multilingual localisation platform',
    subtitle: 'Translation workflow platform for multilingual localisation and quality control',
    date: 'August 2026',
    description:
      'A localisation system for keywords, sentences, and official project dictionaries, designed for translators, proofreaders, language leads, and administrators.',
    impact: 'Supports high-quality multilingual translation delivery through exclusive batches, sample review, dictionary QA, and translation memory.',
    summary:
      'Tafsiri is a multilingual localisation system for keywords, sentences, and official project dictionaries. Translators work in exclusive 300-item batches, proofreaders validate the sample review path, and approved work is stored in translation memory and the term base.',
    overview:
      'The system supports end-to-end localisation from project import to approved delivery. It combines translation memory, dictionary QA, batch exclusivity rules, proofreader review, and delivery export tools to keep translation quality consistent while protecting contributor workflows.',
    stack: ['Translation memory', 'Dictionary QA', 'Batch review', 'Delivery exports'],
    features: [
      'Exclusive translation batches of 300 items with proofreader sample review.',
      'Keyword and sentence workspaces with QA, TM suggestions, and concordance search.',
      'Versioned dictionary and term-base checks before final submission.',
      '10% sample review by proofreaders with edit-approve or reject decisions.',
      'Delivery exports, monitoring, payroll calculation, and contributor performance reporting.',
    ],
    users: [
      { role: 'Translator', description: 'Claim a language batch, draft translations, run QA checks, and submit completed work.' },
      { role: 'Proofreader', description: 'Review the 30-item sample, approve, edit-approve, or reject with LQA reasons.' },
      { role: 'Language lead', description: 'Activate users, resolve disputes, manage QA exceptions, and monitor language teams.' },
      { role: 'Admin', description: 'Create projects, import files, manage users, export deliverables, and oversee batch health.' },
    ],
    useCases: [
      'Create a project and import keyword or sentence files.',
      'Activate users and assign them to languages before work starts.',
      'Claim exclusive 300-item packs and translate in the keyword or sentence workspace.',
      'Run QA checks and use translation memory to improve consistency.',
      'Submit a batch for proofreader sample review.',
      'Approve or return the whole batch based on sample outcomes.',
    ],
    frontend: [
      'My batches and task-oriented dashboard for workers by role and language.',
      'Keyword and sentence workspace screens with dictionary hints and QA feedback.',
      'Sample review screens with approval, edit-approve, and reject actions.',
      'Admin and lead monitoring views for counts, batch health, and performance.',
      'Public auth flows for signup, forgot-password, and complete-profile onboarding.',
    ],
    backend: [
      'Next.js 15 app with server actions and authorisation gates before every mutation.',
      'Supabase Postgres and Storage to maintain structured translation data and revision history.',
      'Translation memory triggers and dictionary QA checks that prevent silent approval of bad content.',
      'Role-based access and language scoping across translators, proofreaders, leads, and admins.',
      'Exports and reports built around approved counts, batch state, and language-specific performance.',
    ],
    details: [
      ['Batch model', 'Exclusive 300-item packs with sample review'],
      ['Quality controls', 'Dictionary QA, structural QA, translation memory, and revision logs'],
      ['Proofreader gate', '30-item check with pass/fail outcome for the whole batch'],
      ['Delivery', 'CSV and Excel exports with contributor performance tracking'],
      ['Governance', 'Language leads and admins manage team activation and exceptions'],
    ],
    access_url: '',
    is_published: true,
    order: 2,
  },
];
